# notifications:
#   webhook:
#     type: webhook
#     config:
#       url: 'https://httpbin.org/post'
#   webhook1:
#     type: webhook
#     config:
#       url: 'https://httpbin.org/post'
rules:
  scan-rules:
  skip-rules:
    - accurics.azure.NS.272