name: Dotnet CD
on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
        default: "dotnet-build-artifact"
        description: "The name of the published artifact to be deployed"

jobs:
  build-dotnet:
    name: Azure deployment
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ${{ inputs.working-directory }}
    env:
    #   PROJECT_ROOT_PATH: "${{ github.workspace }}/${{ inputs.working-directory }}"
    #   PROJECT_FULL_PATH: "${{ github.workspace }}/${{ inputs.working-directory }}/${{ inputs.sln-project-path }}"
    #   TEST_FULL_PATH: "${{ github.workspace }}/${{ inputs.working-directory }}Test/${{ inputs.test-project-path }}"
    #   AZURE_FUNCTIONAPP_NAME: "ghal-dev-fa"
      AZURE_WEBAPP_NAME: "ghal-dev-wa"
    #   DOTNET_VERSION: ${{ inputs.dotnet-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-build-artifact
          path: './downloads'

      - name: Dir downloads
        run: ls -lah ./downloads

      - name: Unzip build archive
        run: unzip ./downloads/*.zip -d ./extracted

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './extracted'