name: terraform-ci.yml
on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  WORKFLOW_BASE_PATH: '$GITHUB_WORKSPACE'

permissions: read-all

jobs:
  terraform:
    name: "Terraform deploy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ vars.TERRAFORM_ROOT_DIRECTORY }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NOdeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4

      - name: Terrformm init
        run: terraform init

      - name: Terrform plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -no-color
