name: Terraform CD
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

permissions: read-all

jobs:
  terraform:
    name: Terraform workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: YouGitMoreWithLes-Insight/.github/.github/workflows/terraform-cd.yml@main
    secrets: inherit
    permissions:
      id-token: write
