name: Terraform CI
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "src/InfrastructureAsCode/**"
    
  pull_request:
    branches: ["main"]
    paths:
      - "src/InfrastructureAsCode/**"

permissions: read-all

jobs:
  linter:
    name: Linter workflow
    uses: YouGitMoreWithLes-Insight/.github/.github/workflows/lint.yml@main
    with:
      branch: main
    secrets: inherit
    permissions:
      contents: write

  terraform:
    name: Terraform workflow
    uses: YouGitMoreWithLes-Insight/.github/.github/workflows/terraform-ci.yml@main
    secrets: inherit
    permissions:
      id-token: write
